#!/bin/bash
# Off-host test of deploy/character-profile-db/scripts/{install,uninstall,backup}.sh
# against mocked pct/zfs/docker/date/id/stat/chown/timeout (no root or Proxmox needed).
# Run from anywhere: bash deploy/character-profile-db/tests/run_tests.sh
#
# The backup.sh checks (section 17, WP-02 T02.1-T02.8) are skipped while
# scripts/backup.sh does not exist yet (it is generated by the qwen harness),
# unless CHARACTER_V4_STRICT=1, which runs them regardless.
set -u

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../scripts" && pwd)"
# Git on Windows doesn't record the executable bit, so set it here: a mock
# that isn't executable fails with "Permission denied" instead of running.
chmod +x "$HERE"/mockbin/*
export PATH="$HERE/mockbin:$PATH"
DS="tank_0/utilities/character-profile-db"

PASS=0
FAIL=0
check() {  # check <description> <command...>
    local desc="$1"; shift
    if "$@"; then PASS=$((PASS + 1)); echo "  ok   $desc"
    else FAIL=$((FAIL + 1)); echo "  FAIL $desc"; fi
}

fresh_state() {
    export MOCK_STATE
    MOCK_STATE="$(mktemp -d)"
    : > "$MOCK_STATE/calls"
    : > "$MOCK_STATE/containers"
    # mafober's real CT 101 already uses mp0..mp6
    printf 'mp%d: /tank_0/x%d,mp=/tank_0/x%d\n' 0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 > "$MOCK_STATE/ctconfig"
    echo "tank_0/utilities" > "$MOCK_STATE/datasets"
}

run_script() {  # run_script <script> <stdin> [args...] ; sets RC and OUT
    local script="$1" input="$2"; shift 2
    OUT="$(printf '%s\n' "$input" | bash "$REPO/$script" "$@" 2>&1)"
    RC=$?
}

mutations() { grep -E '^(zfs (create|destroy)|pct (set|reboot)|chown)' "$MOCK_STATE/calls" || true; }
has_line()  { grep -q -- "$2" <<<"$1"; }

echo "== syntax =="
check "install.sh parses"   bash -n "$REPO/install.sh"
check "uninstall.sh parses" bash -n "$REPO/uninstall.sh"

echo "== 1. fresh install, mount not live yet, no --reboot-ct =="
fresh_state
run_script install.sh ""
check "exits 3 (stop before deploy)"        test "$RC" -eq 3
check "dataset created with 16K records"    grep -q "zfs create -o recordsize=16K -o atime=off $DS" "$MOCK_STATE/calls"
check "owner set to 999:999"                grep -qx "999:999" "$MOCK_STATE/owner"
check "mount added at next free index mp7"  grep -q "^mp7: $MOCK_STATE/fs/$DS,mp=/$DS$" "$MOCK_STATE/ctconfig"
check "warns not to deploy yet"             has_line "$OUT" "Do NOT deploy the stack"
check "no reboot without the flag"          bash -c "! grep -q 'pct reboot' '$MOCK_STATE/calls'"

echo "== 2. re-run is idempotent =="
: > "$MOCK_STATE/calls"
run_script install.sh ""
check "still exits 3"                       test "$RC" -eq 3
check "no mutations on re-run"              test -z "$(mutations)"
check "reports existing dataset"            has_line "$OUT" "already exists"
check "reports existing mount key"          has_line "$OUT" "already has mp7"
check "only one mp line for the dataset"    test "$(grep -c "character-profile-db" "$MOCK_STATE/ctconfig")" -eq 1

echo "== 3. --reboot-ct, wrong confirmation =="
run_script install.sh "yes" --reboot-ct
check "exits 3"                             test "$RC" -eq 3
check "did not reboot"                      bash -c "! grep -q 'pct reboot' '$MOCK_STATE/calls'"

echo "== 4. --reboot-ct, typed confirmation =="
run_script install.sh "reboot 101" --reboot-ct
check "exits 0"                             test "$RC" -eq 0
check "rebooted CT 101"                     grep -q "pct reboot 101" "$MOCK_STATE/calls"
check "prints Portainer next steps"         has_line "$OUT" "Stacks -> Add stack"

echo "== 5. --dry-run on a fresh host changes nothing =="
fresh_state
run_script install.sh "" --dry-run
check "exits 0"                             test "$RC" -eq 0
check "no mutations"                        test -z "$(mutations)"
check "shows the zfs create it would run"   has_line "$OUT" "\[dry-run\] zfs create"
check "shows the pct set it would run"      has_line "$OUT" "\[dry-run\] pct set 101 -mp7"

echo "== 6. CT stopped =="
fresh_state
touch "$MOCK_STATE/ct_stopped"
run_script install.sh ""
check "exits 1"                             test "$RC" -eq 1
check "no mutations"                        test -z "$(mutations)"

echo "== 7. --verify, everything healthy =="
fresh_state
run_script install.sh "reboot 101" --reboot-ct >/dev/null
printf '%s\n' character-profile-db character-profile-db-init > "$MOCK_STATE/containers"
mkdir -p "$MOCK_STATE/fs/$DS/pgdata" && echo 16 > "$MOCK_STATE/fs/$DS/pgdata/PG_VERSION"
run_script install.sh "" --verify
check "exits 0"                             test "$RC" -eq 0
check "prints connection settings"          has_line "$OUT" "CHARACTER_DB_PORT=5433"
check "warns about the filtered port"       has_line "$OUT" "not reachable from this host"

echo "== 8. --verify, init failed and data not on dataset =="
echo "exited 1" > "$MOCK_STATE/initstate"
rm -f "$MOCK_STATE/fs/$DS/pgdata/PG_VERSION"
run_script install.sh "" --verify
check "exits 1"                             test "$RC" -eq 1
check "reports the init failure"            has_line "$OUT" "FAIL character-profile-db-init"
check "reports data not on dataset"         has_line "$OUT" "is not writing to"

echo "== 9. uninstall while the stack still exists =="
: > "$MOCK_STATE/calls"
run_script uninstall.sh ""
check "exits 1"                             test "$RC" -eq 1
check "no mutations"                        test -z "$(mutations)"
check "tells you to delete the stack"       has_line "$OUT" "Delete the character-profile-db stack"

echo "== 10. uninstall (stack deleted): removes mount, keeps data =="
: > "$MOCK_STATE/containers"
run_script uninstall.sh ""
check "exits 0"                             test "$RC" -eq 0
check "mount point removed"                 bash -c "! grep -q character-profile-db '$MOCK_STATE/ctconfig'"
check "other mount points untouched"        test "$(grep -c '^mp' "$MOCK_STATE/ctconfig")" -eq 7
check "dataset kept"                        grep -qx "$DS" "$MOCK_STATE/datasets"
check "no destroy"                          bash -c "! grep -q 'zfs destroy' '$MOCK_STATE/calls'"

echo "== 11. --purge-data while the old mount is still live in the CT =="
run_script uninstall.sh "$DS" --purge-data
check "exits 1"                             test "$RC" -eq 1
check "dataset kept"                        grep -qx "$DS" "$MOCK_STATE/datasets"
check "asks for a CT reboot first"          has_line "$OUT" "still mounted inside CT"

echo "== 12. --purge-data after the reboot, wrong confirmation =="
rm -f "$MOCK_STATE/mounted"
run_script uninstall.sh "nope" --purge-data
check "exits 1"                             test "$RC" -eq 1
check "dataset kept"                        grep -qx "$DS" "$MOCK_STATE/datasets"

echo "== 13. --purge-data --dry-run =="
: > "$MOCK_STATE/calls"
run_script uninstall.sh "" --purge-data --dry-run
check "exits 0"                             test "$RC" -eq 0
check "no mutations"                        test -z "$(mutations)"
check "shows the destroy it would run"      has_line "$OUT" "\[dry-run\] zfs destroy -r $DS"

echo "== 14. --purge-data, typed dataset name =="
run_script uninstall.sh "$DS" --purge-data
check "exits 0"                             test "$RC" -eq 0
check "dataset destroyed"                   bash -c "! grep -qx '$DS' '$MOCK_STATE/datasets'"
check "parent dataset untouched"            grep -qx "tank_0/utilities" "$MOCK_STATE/datasets"

echo "== 15. bad option =="
run_script install.sh "" --bogus
check "install.sh rejects unknown option"   test "$RC" -eq 1
run_script uninstall.sh "" --bogus
check "uninstall.sh rejects unknown option" test "$RC" -eq 1

echo "== 16. read-only role (character_reader) in the deploy package =="
COMPOSE_FILE="$HERE/../docker-compose.yml"
ENV_EXAMPLE="$HERE/../.env.example"
check "init command creates character_reader" grep -q 'character_reader' "$COMPOSE_FILE"
check "init command creates the role idempotently" grep -q 'IF NOT EXISTS' "$COMPOSE_FILE"
check "init command is gated on CHARACTER_READER_PASSWORD" grep -q 'CHARACTER_READER_PASSWORD' "$COMPOSE_FILE"
check ".env.example has an empty CHARACTER_READER_PASSWORD line" grep -qx 'CHARACTER_READER_PASSWORD=' "$ENV_EXAMPLE"
# The init script is a YAML block scalar: extract it (strip the 8-space block
# indent, unescape compose's $$) and make sure bash can parse it. Catches an
# indented heredoc terminator, which grep checks above cannot see.
INIT_SH="$(mktemp)"
awk '/^  init:/{s=1} s&&/^    command:/{c=1;next} c&&/^      - \|/{b=1;next}
     b&&/^    [a-z_]+:/{exit} b{sub(/^        /,""); gsub(/\$\$/,"$"); print}' \
    "$COMPOSE_FILE" > "$INIT_SH"
check "init command was extracted" test -s "$INIT_SH"
check "init command parses as bash" bash -n "$INIT_SH"
check "init heredoc terminators are unindented" bash -c "! grep -qE '^[[:space:]]+SQL\$' '$INIT_SH'"
rm -f "$INIT_SH"

echo "== 17. backup.sh (WP-02) =="
BACKUP_SH="$REPO/backup.sh"

has_text() { grep -qF -- "$2" <<<"$1"; }                       # fixed string, not a regex
dry_line() { grep -F -- "[dry-run]" <<<"$1" | grep -qF -- "$2"; } # a [dry-run] line containing $2
backup_row() { grep -i "backup_runs" "$MOCK_STATE/sql" 2>/dev/null | grep -q "'$1'"; }
backup_mutations() {
    grep -E '^(zfs (snapshot|destroy)|docker exec .*(pg_dump|pg_restore))' "$MOCK_STATE/calls" || true
    grep -i "backup_runs" "$MOCK_STATE/sql" 2>/dev/null || true
}
count_dumps() { ls "$1" | grep -cE '^character_profile_[0-9]{8}_[0-9]{4}\.dump$'; }
count_snaps() { grep -cE "^$DS@auto-[0-9]{8}\$" "$MOCK_STATE/snapshots"; }

backup_state() {  # backup_state [now] : fresh mocks for backup.sh, clock pinned to [now]
    fresh_state
    echo "$DS" >> "$MOCK_STATE/datasets"
    echo "character-profile-db" > "$MOCK_STATE/containers"
    echo "${1:-2026-10-06 00:30:00}" > "$MOCK_STATE/now"          # a Tuesday
    : > "$MOCK_STATE/snapshots"
    export BACKUP_ROOT="$MOCK_STATE/backups"
    mkdir -p "$BACKUP_ROOT/daily" "$BACKUP_ROOT/weekly"
    printf 'characters|8\nexperience_events|120\n' > "$MOCK_STATE/counts.character_profile"
    cp "$MOCK_STATE/counts.character_profile" "$MOCK_STATE/counts.character_profile_drill"
}
seed_dumps() {  # seed_dumps <dir> <n> : character_profile_202609{01..n}_0030.dump
    local i f
    for ((i = 1; i <= $2; i++)); do
        printf -v f 'character_profile_202609%02d_0030.dump' "$i"
        echo "seeded $f" > "$1/$f"
    done
}
seed_snapshots() {  # 20 @auto- snapshots of $DS, deliberately NOT in date order
    local i
    for i in 11 3 20 7 1 15 9 18 5 13 2 19 8 16 4 12 6 17 10 14; do
        printf '%s@auto-202609%02d\n' "$DS" "$i" >> "$MOCK_STATE/snapshots"
    done
}
backup_listing() { (cd "$BACKUP_ROOT" && find . -type f | sort); sort "$MOCK_STATE/snapshots"; }

backup_checks() {
    local D W before

    echo "-- T02.1 --dry-run prints the commands and writes nothing"
    backup_state
    D="$BACKUP_ROOT/daily"; W="$BACKUP_ROOT/weekly"
    seed_dumps "$D" 20; seed_dumps "$W" 10; seed_snapshots
    before="$(backup_listing)"
    run_script backup.sh "" --dry-run
    check "B1 --dry-run exits 0"                  test "$RC" -eq 0
    check "B1 prints the pg_dump command"         dry_line "$OUT" "pct exec 101 -- docker exec character-profile-db pg_dump -U postgres -Fc character_profile"
    check "B1 prints the zfs snapshot command"    dry_line "$OUT" "zfs snapshot $DS@auto-20261006"
    check "B1 prints the prune of a daily dump"   dry_line "$OUT" "daily/character_profile_20260901_0030.dump"
    check "B1 prints the prune of a snapshot"     dry_line "$OUT" "zfs destroy $DS@auto-20260901"
    check "B1 files and snapshots unchanged"      test "$before" == "$(backup_listing)"
    check "B1 no dump, snapshot, destroy or row"  test -z "$(backup_mutations)"

    echo "-- T02.2 a normal run dumps into daily/"
    backup_state
    D="$BACKUP_ROOT/daily"; W="$BACKUP_ROOT/weekly"
    run_script backup.sh ""
    check "B2 exits 0"                            test "$RC" -eq 0
    check "B2 runs pg_dump in the DB container"   grep -qF "pct exec 101 -- docker exec character-profile-db pg_dump -U postgres -Fc character_profile" "$MOCK_STATE/calls"
    check "B2 writes daily/character_profile_<stamp>.dump" test -s "$D/character_profile_20261006_0030.dump"
    check "B2 the dump file holds pg_dump's output" grep -q "PGDMP mock dump of character_profile" "$D/character_profile_20261006_0030.dump"
    check "B2 takes the @auto- snapshot"          grep -qx "$DS@auto-20261006" "$MOCK_STATE/snapshots"
    check "B2 writes an ok backup_runs row"       backup_row ok
    check "B2 no weekly copy on a Tuesday"        test -z "$(ls -A "$W")"

    echo "-- T02.3 on a Sunday it also copies to weekly/"
    backup_state "2026-10-04 00:30:00"
    D="$BACKUP_ROOT/daily"; W="$BACKUP_ROOT/weekly"
    run_script backup.sh ""
    check "B3 exits 0"                            test "$RC" -eq 0
    check "B3 writes the daily dump"              test -s "$D/character_profile_20261004_0030.dump"
    check "B3 copies it to weekly/"               cmp -s "$D/character_profile_20261004_0030.dump" "$W/character_profile_20261004_0030.dump"

    echo "-- T02.4 pruning keeps 14 daily, 8 weekly, 14 @auto- snapshots"
    backup_state
    D="$BACKUP_ROOT/daily"; W="$BACKUP_ROOT/weekly"
    seed_dumps "$D" 20; seed_dumps "$W" 10; seed_snapshots
    run_script backup.sh ""
    check "B4 exits 0"                            test "$RC" -eq 0
    check "B4 keeps 14 daily dumps"               test "$(count_dumps "$D")" -eq 14
    check "B4 keeps today's dump"                 test -f "$D/character_profile_20261006_0030.dump"
    check "B4 keeps the 13 newest seeded dumps"   test -f "$D/character_profile_20260908_0030.dump"
    check "B4 drops the older daily dumps"        test ! -e "$D/character_profile_20260907_0030.dump"
    check "B4 keeps 8 weekly dumps"               test "$(count_dumps "$W")" -eq 8
    check "B4 drops the oldest weekly dumps"      test ! -e "$W/character_profile_20260902_0030.dump"
    check "B4 keeps the newer weekly dumps"       test -f "$W/character_profile_20260903_0030.dump"
    check "B4 keeps 14 @auto- snapshots"          test "$(count_snaps)" -eq 14
    check "B4 keeps today's snapshot"             grep -qx "$DS@auto-20261006" "$MOCK_STATE/snapshots"
    check "B4 keeps the newer snapshots"          grep -qx "$DS@auto-20260908" "$MOCK_STATE/snapshots"
    check "B4 destroys the older snapshots"       bash -c "! grep -qx '$DS@auto-20260907' '$MOCK_STATE/snapshots'"

    echo "-- T02.5 pruning ignores names outside the pattern"
    backup_state
    D="$BACKUP_ROOT/daily"
    seed_dumps "$D" 20; seed_snapshots
    for f in notes.txt character_profile_manual.dump other_20200101_0000.dump character_profile_20200101_0000.dump.partial; do
        echo keep > "$D/$f"
    done
    echo "$DS@manual-before-upgrade" >> "$MOCK_STATE/snapshots"
    echo "$DS@auto-notadate" >> "$MOCK_STATE/snapshots"
    run_script backup.sh ""
    check "B5 exits 0"                            test "$RC" -eq 0
    check "B5 keeps notes.txt"                    test -f "$D/notes.txt"
    check "B5 keeps character_profile_manual.dump" test -f "$D/character_profile_manual.dump"
    check "B5 keeps other_20200101_0000.dump"     test -f "$D/other_20200101_0000.dump"
    check "B5 keeps a .dump.partial"              test -f "$D/character_profile_20200101_0000.dump.partial"
    check "B5 still prunes matching dumps to 14"  test "$(count_dumps "$D")" -eq 14
    check "B5 keeps @manual-before-upgrade"       grep -qx "$DS@manual-before-upgrade" "$MOCK_STATE/snapshots"
    check "B5 keeps @auto-notadate"               grep -qx "$DS@auto-notadate" "$MOCK_STATE/snapshots"
    check "B5 still prunes @auto- snapshots to 14" test "$(count_snaps)" -eq 14

    echo "-- T02.6 a failed pg_dump exits non-zero and records failed"
    backup_state
    touch "$MOCK_STATE/pg_dump_fail"
    run_script backup.sh ""
    check "B6 exits non-zero"                     test "$RC" -ne 0
    check "B6 writes a failed backup_runs row"    backup_row failed

    echo "-- T02.7 --restore-drill creates, compares and drops character_profile_drill"
    backup_state
    seed_dumps "$BACKUP_ROOT/daily" 3
    run_script backup.sh "" --restore-drill
    check "B7 exits 0 when the counts match"      test "$RC" -eq 0
    check "B7 creates the drill database"         grep -qiE "create database \"?character_profile_drill" "$MOCK_STATE/sql"
    check "B7 runs pg_restore into the drill DB"  bash -c "grep -F 'pg_restore' '$MOCK_STATE/calls' | grep -qF 'character_profile_drill'"
    check "B7 restores the newest dump"           grep -qF "character_profile_20260903_0030.dump" "$MOCK_STATE/restored"
    check "B7 counts rows in the live DB"         grep -qE "^character_profile: .*count\(" "$MOCK_STATE/sql"
    check "B7 counts rows in the drill DB"        grep -qE "^character_profile_drill: .*count\(" "$MOCK_STATE/sql"
    check "B7 drops the drill database"           grep -qiE "drop database( if exists)? \"?character_profile_drill" "$MOCK_STATE/sql"
    : > "$MOCK_STATE/sql"
    printf 'characters|8\nexperience_events|119\n' > "$MOCK_STATE/counts.character_profile_drill"
    run_script backup.sh "" --restore-drill
    check "B7 a count mismatch exits 1"           test "$RC" -eq 1
    check "B7 names the mismatched table"         has_text "$OUT" "experience_events"
    check "B7 drops the drill DB after a mismatch" grep -qiE "drop database( if exists)? \"?character_profile_drill" "$MOCK_STATE/sql"

    echo "-- T02.8 not running as root exits 1"
    backup_state
    touch "$MOCK_STATE/not_root"
    run_script backup.sh ""
    check "B8 exits 1"                            test "$RC" -eq 1
    check "B8 says it must run as root"           grep -qi "root" <<<"$OUT"
    check "B8 touches nothing"                    test ! -s "$MOCK_STATE/calls"
    unset BACKUP_ROOT
}

if [[ -f "$BACKUP_SH" || "${CHARACTER_V4_STRICT:-}" == "1" ]]; then
    check "backup.sh parses" bash -n "$BACKUP_SH"
    backup_checks
else
    echo "  skip backup.sh checks: v4 WP-02: code pending (qwen harness)"
fi

echo ""
echo "passed: $PASS  failed: $FAIL"
[[ $FAIL -eq 0 ]]
