"""Tests for generators/coder/ — the coder campaign's offline episode
generator (session_log_parser.py + build_library.py), moved out of the
platform per CONTRACT.md §9 (docs/campaign_platform_build.md's "Generators
(separate, one per campaign)" split).

The redaction tests are the load-bearing ones, unchanged from the original
tests/test_session_log_parser.py this file replaces: a regression there is
a privacy incident, not a cosmetic bug. The new tests added at the bottom
cover the schema-emission half of the move: the event->primitive mapping,
sidecar inlining (no more detail_file sidecars survive into the episode),
the LEAK_AUDIT refusal path, and an end-to-end pass through
app/episode_schema.py's validator under the coder campaign.
"""
import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "app"))
sys.path.insert(0, str(ROOT / "generators" / "coder"))

from session_log_parser import (  # noqa: E402
    clean_user_text,
    parse_session,
    parse_tool_detail,
    redact,
)

import build_library  # noqa: E402
from episode_schema import normalize_episode, validate_episode  # noqa: E402
from primitives import estimate_scene_seconds, load_primitives  # noqa: E402


# ── redact ───────────────────────────────────────────────────────────────────
@pytest.mark.parametrize("raw,expected_absent,expected_marker", [
    ("push to 8.45.212.7:9092 now", "8.45.212", "[ip]"),
    ("ollama at 100.37.208.112 is down", "100.37", "[ip]"),
    ("partial tailnet ref 100.37.208:8090 too", "100.37", "[ip]"),
    ("key sk-ant-api03-AbCdEfGh123456 leaked", "sk-ant-api03", "[api-key]"),
    ("token ghp_abcdefghijklmnopqrst123 here", "ghp_a", "[github-token]"),
    ("stream key live_abcdefghijklmnop_x", "live_a", "[stream-key]"),
    ("mail frogger5687@gmail.com please", "@gmail", "[email]"),
    ("POSTGRES_PASSWORD=hunter2 in the env", "hunter2", "[password]"),
    ("export PGPASSWORD='tr0ub4dor'", "tr0ub4dor", "[password]"),
    ('config had "password": "s3cr3t!x" set', "s3cr3t", "[password]"),
    ("yaml style password: hunter2 here", "hunter2", "[password]"),
    ("client_secret = abc123xyz in settings", "abc123xyz", "[password]"),
    ("psql --password hunter2 -h db", "hunter2", "[password]"),
    ("dsn postgres://admin:hunter2@10.0.0.5/db", "hunter2", "[password]"),
    # double-nested quoting, as in psql -v var="'value'"
    ("-v pg_password=\"'hunter2'\" -f setup.sql", "hunter2", "[password]"),
])
def test_redact_scrubs_sensitive_patterns(raw, expected_absent, expected_marker):
    result = redact(raw)
    assert expected_absent not in result
    assert expected_marker in result


@pytest.mark.parametrize("raw", [
    "connect to 192.168.1.120:9092 now",
    "partial LAN ref 192.168.1:8090 too",
    "hosts 10.0.5.3 and 172.16.0.9 and 127.0.0.1 up",
])
def test_redact_preserves_private_ips(raw):
    assert redact(raw) == raw


def test_redact_url_credentials_keep_user_and_private_host():
    result = redact("dsn postgres://admin:hunter2@192.168.1.5/db")
    assert result == "dsn postgres://admin:[password]@192.168.1.5/db"


def test_redact_leaves_empty_password_assignment_alone():
    # .env templates legitimately show "POSTGRES_PASSWORD=" with no value
    text = "POSTGRES_PASSWORD=\nPOSTGRES_USER=vtubers"
    assert redact(text) == text


@pytest.mark.parametrize("raw", [
    r"C:\Users\frogg\OneDrive\proj\file.py",
    r"C:\\Users\\frogg\\.claude\\settings.json",
    "/c/Users/frogg/code/x.py",
    "/home/frogg/app",
    "c--Users-frogg-OneDrive-Documents-codeProjects-virtualTubers",
    "-rw-r--r-- 1 frogg 197609 2179 Jul  1 config",  # ls -la owner column
])
def test_redact_scrubs_username_in_all_forms(raw):
    assert "frogg" not in redact(raw)


def test_redact_leaves_ordinary_text_alone():
    text = "The tester reports test_passed to the manager after pytest runs."
    assert redact(text) == text


# ── clean_user_text ──────────────────────────────────────────────────────────
def test_clean_user_text_drops_pure_noise_turn():
    noise = ("<local-command-caveat>Caveat: generated by user...</local-command-caveat>\n"
             "<command-name>/model</command-name>")
    assert clean_user_text(noise) == ""


def test_clean_user_text_keeps_real_request_strips_inline_noise():
    mixed = ("<system-reminder>ignore this</system-reminder>\n"
             "Hey claude, please fix the bug in agent.py")
    cleaned = clean_user_text(mixed)
    assert "fix the bug" in cleaned
    assert "system-reminder" not in cleaned


# ── parsing a synthetic session ──────────────────────────────────────────────
CONVERSATION_MD = """# Claude Session Log

**Project:** virtualTubers
**Session ID:** `abc123`
**Date:** 2026-07-02_04-27-00

---

## User

Please add a heartbeat to agent.py

## Assistant

I'll look at the agent loop first.

> **Tool:** Read
> **Input:** c:\\Users\\frogg\\proj\\app\\agent.py
> **Output:** 1\t#!/usr/bin/env python3...
> [Full details](tool_001_Read.md)

> **Tool:** Edit **ERROR**
> **Input:** c:\\Users\\frogg\\proj\\app\\agent.py
> **Output:** old_string not found
> [Full details](tool_002_Edit.md)

Done — heartbeat added.

## User

<local-command-stdout>Set model to claude-fable-5</local-command-stdout>
"""

TOOL_EDIT_MD = """# Tool Call #2: Edit

## Input

**File:** `c:\\Users\\frogg\\proj\\app\\agent.py`

**Old:**
```
i = 0
```

**New:**
```
i = 0  # tick counter
```

## Output

```
old_string not found
```
"""


@pytest.fixture
def session_dir(tmp_path):
    (tmp_path / "conversation.md").write_text(CONVERSATION_MD, encoding="utf-8")
    (tmp_path / "tool_002_Edit.md").write_text(TOOL_EDIT_MD, encoding="utf-8")
    return tmp_path


def test_parse_session_structure(session_dir):
    script = parse_session(session_dir)
    assert script["project"] == "virtualTubers"
    assert script["session_id"] == "abc123"
    types = [e["type"] for e in script["events"]]
    # noise-only trailing user turn must be dropped
    assert types == ["user_message", "assistant_text", "tool_call", "tool_call",
                     "assistant_text"]


def test_parse_session_error_flag_and_detail(session_dir):
    script = parse_session(session_dir)
    edit = script["events"][3]
    assert edit["tool"] == "Edit"
    assert edit["error"] is True
    assert edit["detail"]["old"] == "i = 0"
    assert edit["detail"]["new"] == "i = 0  # tick counter"


def test_parse_session_output_is_fully_redacted(session_dir):
    dumped = json.dumps(parse_session(session_dir))
    assert "frogg" not in dumped


# ── tool detail edge cases ───────────────────────────────────────────────────
def test_shell_detail_with_non_dict_json_does_not_crash(tmp_path):
    detail_md = "# Tool Call #1: Bash\n\n## Input\n\n```json\ntrue\n```\n\n## Output\n\n```\nok\n```\n"
    p = tmp_path / "tool_001_Bash.md"
    p.write_text(detail_md, encoding="utf-8")
    detail = parse_tool_detail(p, "Bash")
    assert detail["command"] == "true"
    assert detail["output"] == "ok"


def test_missing_detail_file_returns_none(tmp_path):
    assert parse_tool_detail(tmp_path / "nope.md", "Edit") is None


# ── event -> primitive mapping (CONTRACT.md §9b's payload contract) ─────────
@pytest.mark.parametrize("event,expected_primitive,expected_payload", [
    (
        {"type": "user_message", "text": "hello boss"},
        "show_boss_message",
        {"text": "hello boss"},
    ),
    (
        {"type": "assistant_text", "text": "hi stream"},
        "show_coder_line",
        {"text": "hi stream", "name": "KODI-7"},
    ),
    (
        {"type": "tool_call", "tool": "Bash", "error": False, "input_summary": "ls",
         "detail": {"command": "ls -la", "output": "total 0"}},
        "show_command",
        {"command": "ls -la", "output": "total 0"},
    ),
    (
        {"type": "tool_call", "tool": "PowerShell", "error": True, "input_summary": "Get-Item x",
         "detail": {"command": "Get-Item x"}},
        "show_command",
        {"command": "Get-Item x", "error": True},
    ),
    (
        {"type": "tool_call", "tool": "Edit", "error": False, "input_summary": "app/x.py",
         "detail": {"file": "app/x.py", "old": "a\nb", "new": "a\nc"}},
        "show_diff",
        {"file": "app/x.py", "hunks": ["- a", "- b", "+ a", "+ c"]},
    ),
    (
        {"type": "tool_call", "tool": "Write", "error": False, "input_summary": "app/y.py",
         "detail": {"file": "app/y.py", "content": "print(1)\n"}},
        "show_write",
        {"file": "app/y.py", "content": "print(1)\n"},
    ),
    (
        {"type": "tool_call", "tool": "Read", "error": False, "input_summary": "app/z.py",
         "detail": {"file": "app/z.py"}},
        "show_read",
        {"file": "app/z.py"},
    ),
    (
        {"type": "tool_call", "tool": "Agent", "error": False,
         "input_summary": "spawn subagent to run tests" * 10},
        "show_tool",
        {"tool": "Agent", "summary": ("spawn subagent to run tests" * 10)[:100]},
    ),
])
def test_event_to_render_maps_every_case(event, expected_primitive, expected_payload):
    """CONTRACT.md §9b's exact table: user_message -> show_boss_message,
    assistant_text -> show_coder_line, Bash/PowerShell -> show_command,
    Edit -> show_diff, Write -> show_write, Read -> show_read, everything
    else -> show_tool. Also covers the `error` flag only being set when
    truthy (show_boss_message/show_coder_line never carry one)."""
    primitive, payload = build_library.event_to_render(event, worker_name="KODI-7")
    assert primitive == expected_primitive
    assert payload == expected_payload


def test_event_to_render_diff_hunks_are_old_block_then_new_block_not_unified():
    """CONTRACT.md §9b: hunks = every pre-edit line prefixed '- ', THEN
    every post-edit line prefixed '+ ', concatenated in that order -- NOT
    interleaved like a real unified diff would be."""
    event = {"type": "tool_call", "tool": "Edit", "error": False,
             "detail": {"file": "f.py", "old": "one\ntwo\nthree", "new": "one\ntwo-b"}}
    _, payload = build_library.event_to_render(event)
    assert payload["hunks"] == ["- one", "- two", "- three", "+ one", "+ two-b"]


def test_event_to_render_show_tool_summary_is_pretruncated_to_100_chars():
    long_summary = "x" * 250
    event = {"type": "tool_call", "tool": "ScheduleWakeup", "error": False,
             "input_summary": long_summary}
    primitive, payload = build_library.event_to_render(event)
    assert primitive == "show_tool"
    assert len(payload["summary"]) == 100


# ── scene grouping / budget splitting ───────────────────────────────────────
def test_events_to_scenes_caps_a_marathon_tool_run_at_max_scene_events():
    """Mirrors the deleted app/revoice.py::plan_scenes's own marathon-run
    split behavior (recovered from git history, tests/test_revoice.py per
    recon_performance.md §6) -- MAX_SCENE_EVENTS still applies as the
    coarse first-pass cap before any budget-based re-splitting."""
    events = [
        {"type": "tool_call", "tool": "Bash", "error": False, "input_summary": f"cmd {i}",
         "detail": {"command": f"cmd {i}"}}
        for i in range(10)
    ]
    primitives_table = load_primitives("coder")
    scenes = build_library.events_to_scenes(
        events, primitives_table=primitives_table, max_scene_seconds=None, worker_name="KODI-7"
    )
    assert [scene["kind"] for scene in scenes] == ["coder_work", "coder_work"]
    assert len(scenes[0]["render"]) == build_library.MAX_SCENE_EVENTS
    assert len(scenes[1]["render"]) == 10 - build_library.MAX_SCENE_EVENTS


def test_split_oversized_work_scene_splits_down_to_budget():
    """CONTRACT.md §9's explicit guidance: the generator's cap should be
    consistent with config/validation.yaml's limits.max_scene_seconds
    budget rather than a second hardcoded number. A tiny budget must force
    a multi-event work chunk to split all the way down to one event per
    scene, since even a single show_command here exceeds that budget."""
    events = [
        {"type": "tool_call", "tool": "Bash", "error": False, "input_summary": "pytest -x",
         "detail": {"command": "pytest -x", "output": "ok\n" * 20}}
        for _ in range(4)
    ]
    primitives_table = load_primitives("coder")
    scenes = build_library._split_oversized_work_scene(events, primitives_table, 1.0, "KODI-7")
    assert len(scenes) == 4
    assert all(len(scene["render"]) == 1 for scene in scenes)


def test_split_oversized_work_scene_is_a_no_op_within_budget():
    events = [
        {"type": "tool_call", "tool": "Read", "error": False, "input_summary": f"f{i}.py",
         "detail": {"file": f"f{i}.py"}}
        for i in range(4)
    ]
    primitives_table = load_primitives("coder")
    scenes = build_library._split_oversized_work_scene(events, primitives_table, 1000.0, "KODI-7")
    assert len(scenes) == 1
    assert len(scenes[0]["render"]) == 4


# ── sidecar inlining (no more detail_file sidecars survive) ─────────────────
WRITE_CONVERSATION_MD = """# Claude Session Log

**Project:** virtualTubers
**Session ID:** `xyz789`
**Date:** 2026-07-10_00-00-00

---

## User

Please add a new helper module.

## Assistant

Sure, adding it now.

> **Tool:** Write
> **Input:** app/foo.py
> **Output:** wrote 1 file
> [Full details](tool_001_Write.md)

Done.
"""

TOOL_WRITE_MD = """# Tool Call #1: Write

## Input

**File:** `app/foo.py`

```
def foo():
    return 42
```

## Output

```
Wrote 1 file
```
"""


@pytest.fixture
def write_session_dir(tmp_path):
    (tmp_path / "conversation.md").write_text(WRITE_CONVERSATION_MD, encoding="utf-8")
    (tmp_path / "tool_001_Write.md").write_text(TOOL_WRITE_MD, encoding="utf-8")
    return tmp_path


def test_sidecar_content_is_inlined_and_detail_file_key_never_survives(write_session_dir):
    """CONTRACT.md §9 / docs/campaign_platform_build.md: 'every string that
    will be spoken or displayed lives in the episode itself.' The sidecar's
    own content (read by session_log_parser.parse_tool_detail at parse
    time) must land inside the built episode's render payload, and the
    literal 'detail_file' key -- session_log_parser's pointer to the
    sidecar filename -- must never appear anywhere in the serialized
    episode. If it did, episode_schema.py's external_refs:reject rule
    would fail this output at validation time (config/validation.yaml)."""
    script = parse_session(write_session_dir)
    primitives_table = load_primitives("coder")
    episode = build_library.build_episode(script, primitives_table=primitives_table)
    serialized = json.dumps(episode)

    assert "def foo" in serialized  # sidecar content made it into the payload
    assert "detail_file" not in serialized


# ── LEAK_AUDIT refusal path ──────────────────────────────────────────────────
def test_main_refuses_to_write_and_exits_nonzero_when_leak_audit_matches(tmp_path, monkeypatch, capsys):
    """LEAK_AUDIT is the belt-and-braces re-scan over the FULLY SERIALIZED
    episode, independent of session_log_parser's own redact() -- this is
    what catches a leak that somehow slipped past upstream redaction. Since
    real redaction already scrubs everything session_log_parser.parse_session
    produces, this test simulates the "something got through anyway" case
    by monkeypatching parse_session itself to hand back text redact() never
    touched -- proving main() refuses to write and reports a nonzero exit
    rather than trusting the episode just because it validated structurally."""
    logs_dir = tmp_path / "logs"
    session_dir = logs_dir / "2026-01-01_00-00-00_deadbeef"
    session_dir.mkdir(parents=True)
    out_dir = tmp_path / "out"

    def fake_parse_session(_dir):
        return {
            "source": session_dir.name, "project": "x", "session_id": "1", "date": "d",
            "events": [
                {"type": "user_message", "text": "please fix the leak"},
                {"type": "assistant_text", "text": "on it, frogg mentioned this before"},
                {"type": "tool_call", "tool": "Bash", "error": False,
                 "input_summary": "echo hi", "output_summary": "", "detail_file": None,
                 "detail": {"command": "echo hi"}},
                {"type": "tool_call", "tool": "Read", "error": False,
                 "input_summary": "config/worker.yaml", "output_summary": "",
                 "detail_file": None, "detail": {"file": "config/worker.yaml"}},
                {"type": "assistant_text", "text": "all done"},
            ],
        }

    monkeypatch.setattr(build_library, "parse_session", fake_parse_session)
    exit_code = build_library.main(["--logs", str(logs_dir), "--out", str(out_dir), "--min-events", "1"])

    assert exit_code == 1
    assert not list(out_dir.glob("*.json"))
    assert "LEAK" in capsys.readouterr().out


# ── end-to-end: a generated episode validates cleanly under the coder campaign
def test_generated_episode_passes_episode_schema_validation_under_coder_campaign(session_dir):
    """The design doc's 'same config and same engine on both sides' promise
    (docs/campaign_platform_build.md's Validator section, CONTRACT.md §9):
    an episode this generator builds must pass app/episode_schema.py's
    validate_episode cleanly -- no reject-level Issues -- under the real
    coder campaign's primitive table, validation rules, and narration kinds."""
    from build_library import load_narration_kinds
    from episode_schema import load_rules

    script = parse_session(session_dir)
    primitives_table = load_primitives("coder")
    rules = load_rules()
    kinds = load_narration_kinds()
    max_scene_seconds = (rules.get("limits") or {}).get("max_scene_seconds")

    episode = build_library.build_episode(
        script, primitives_table=primitives_table, max_scene_seconds=max_scene_seconds,
        worker_name="KODI-7",
    )
    normalized = normalize_episode(episode)
    issues = validate_episode(normalized, primitives=primitives_table, rules=rules, kinds=kinds)
    rejecting = [issue for issue in issues if issue.level == "reject"]
    assert rejecting == []

    # And the schema shape itself: cast is TOP-LEVEL, a sibling of meta, not
    # nested inside it (CONTRACT.md §1's explicit warning).
    assert "cast" in normalized
    assert "cast" not in normalized["meta"]
    assert normalized["scenes"], "expected at least one scene"
    for scene in normalized["scenes"]:
        for field in ("speaker", "kind", "text", "fallback", "mode", "render"):
            assert field in scene
