"""Tests for app/session_log_parser.py — canonical replay-script parsing.

The parser feeds panes that get broadcast to a public stream, so the
redaction tests are the load-bearing ones: a regression there is a
privacy incident, not a cosmetic bug.
"""
import json
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "app"))

from session_log_parser import (  # noqa: E402
    clean_user_text,
    parse_session,
    parse_tool_detail,
    redact,
)


# ── redact ───────────────────────────────────────────────────────────────────
@pytest.mark.parametrize("raw,expected_absent,expected_marker", [
    ("connect to 192.168.1.120:9092 now", "192.168", "[ip]"),
    ("ollama at 100.37.208.112 is down", "100.37", "[ip]"),
    ("partial LAN ref 192.168.1:8090 too", "192.168", "[ip]"),
    ("key sk-ant-api03-AbCdEfGh123456 leaked", "sk-ant-api03", "[api-key]"),
    ("token ghp_abcdefghijklmnopqrst123 here", "ghp_a", "[github-token]"),
    ("stream key live_abcdefghijklmnop_x", "live_a", "[stream-key]"),
    ("mail frogger5687@gmail.com please", "@gmail", "[email]"),
])
def test_redact_scrubs_sensitive_patterns(raw, expected_absent, expected_marker):
    result = redact(raw)
    assert expected_absent not in result
    assert expected_marker in result


@pytest.mark.parametrize("raw", [
    r"C:\Users\frogg\OneDrive\proj\file.py",
    r"C:\\Users\\frogg\\.claude\\settings.json",
    "/c/Users/frogg/code/x.py",
    "/home/frogg/app",
    "c--Users-frogg-OneDrive-Documents-codeProjects-virtualTubers",
    "-rw-r--r-- 1 frogg 197609 2179 Jul  1 config",  # ls -la owner column
])
def test_redact_scrubs_username_in_all_forms(raw):
    assert "frogg" not in redact(raw)


def test_redact_leaves_ordinary_text_alone():
    text = "The tester reports test_passed to the manager after pytest runs."
    assert redact(text) == text


# ── clean_user_text ──────────────────────────────────────────────────────────
def test_clean_user_text_drops_pure_noise_turn():
    noise = ("<local-command-caveat>Caveat: generated by user...</local-command-caveat>\n"
             "<command-name>/model</command-name>")
    assert clean_user_text(noise) == ""


def test_clean_user_text_keeps_real_request_strips_inline_noise():
    mixed = ("<system-reminder>ignore this</system-reminder>\n"
             "Hey claude, please fix the bug in agent.py")
    cleaned = clean_user_text(mixed)
    assert "fix the bug" in cleaned
    assert "system-reminder" not in cleaned


# ── parsing a synthetic session ──────────────────────────────────────────────
CONVERSATION_MD = """# Claude Session Log

**Project:** virtualTubers
**Session ID:** `abc123`
**Date:** 2026-07-02_04-27-00

---

## User

Please add a heartbeat to agent.py

## Assistant

I'll look at the agent loop first.

> **Tool:** Read
> **Input:** c:\\Users\\frogg\\proj\\app\\agent.py
> **Output:** 1\t#!/usr/bin/env python3...
> [Full details](tool_001_Read.md)

> **Tool:** Edit **ERROR**
> **Input:** c:\\Users\\frogg\\proj\\app\\agent.py
> **Output:** old_string not found
> [Full details](tool_002_Edit.md)

Done — heartbeat added.

## User

<local-command-stdout>Set model to claude-fable-5</local-command-stdout>
"""

TOOL_EDIT_MD = """# Tool Call #2: Edit

## Input

**File:** `c:\\Users\\frogg\\proj\\app\\agent.py`

**Old:**
```
i = 0
```

**New:**
```
i = 0  # tick counter
```

## Output

```
old_string not found
```
"""


@pytest.fixture
def session_dir(tmp_path):
    (tmp_path / "conversation.md").write_text(CONVERSATION_MD, encoding="utf-8")
    (tmp_path / "tool_002_Edit.md").write_text(TOOL_EDIT_MD, encoding="utf-8")
    return tmp_path


def test_parse_session_structure(session_dir):
    script = parse_session(session_dir)
    assert script["project"] == "virtualTubers"
    assert script["session_id"] == "abc123"
    types = [e["type"] for e in script["events"]]
    # noise-only trailing user turn must be dropped
    assert types == ["user_message", "assistant_text", "tool_call", "tool_call",
                     "assistant_text"]


def test_parse_session_error_flag_and_detail(session_dir):
    script = parse_session(session_dir)
    edit = script["events"][3]
    assert edit["tool"] == "Edit"
    assert edit["error"] is True
    assert edit["detail"]["old"] == "i = 0"
    assert edit["detail"]["new"] == "i = 0  # tick counter"


def test_parse_session_output_is_fully_redacted(session_dir):
    dumped = json.dumps(parse_session(session_dir))
    assert "frogg" not in dumped


# ── tool detail edge cases ───────────────────────────────────────────────────
def test_shell_detail_with_non_dict_json_does_not_crash(tmp_path):
    detail_md = "# Tool Call #1: Bash\n\n## Input\n\n```json\ntrue\n```\n\n## Output\n\n```\nok\n```\n"
    p = tmp_path / "tool_001_Bash.md"
    p.write_text(detail_md, encoding="utf-8")
    detail = parse_tool_detail(p, "Bash")
    assert detail["command"] == "true"
    assert detail["output"] == "ok"


def test_missing_detail_file_returns_none(tmp_path):
    assert parse_tool_detail(tmp_path / "nope.md", "Edit") is None
