#!/usr/bin/env python3
"""scripts/build_table_configs.py: write the live-agent-table worker configs (build plan P3.7).

    .venv/bin/python scripts/build_table_configs.py [config/table/ashiorid.yaml] [--out DIR]

For every seat in the table config: load its SLOT config (`base`, e.g.
config/workers/manager.yaml: voice/avatar/layout/stream stay the slot's), then
set agent.role (table_gm for the GM seat, table_seat otherwise), agent.name and
agent.system_prompt from campaigns/<pack>/cast/<slug>.yaml, agent.tick_rate_ms,
agent.table (the GM gets the table plan; seats get only their own slug and
budgets), and llm. Output: config/workers/table/<slug>.yaml, a generated file:
tests/table/test_table_configs.py fails when a committed file drifts.
"""
import argparse
import copy
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
HEADER = ("# GENERATED by scripts/build_table_configs.py from {src} + {base}.\n"
          "# Do not edit by hand: change the table config and rebuild.\n")
SEAT_PASSES = ("think", "speak")
GM_PASSES = ("direct", "adjudicate", "overrule")
GM_KEYS = ("gm_slug", "gm_seat", "pack_dir", "run_id", "contracts_fixture",
           "only_with_active_players", "start_index", "max_scenes", "think_s", "speak_s",
           "gm_blocks_order")


class _Dumper(yaml.SafeDumper):
    pass


def _str_presenter(dumper, data):
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


_Dumper.add_representer(str, _str_presenter)


def _cast(pack, slug):
    path = REPO / "campaigns" / pack / "cast" / f"{slug}.yaml"
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _seat_of(seats):
    out = {}
    for s in seats:
        for variant in (s["slug"], s["slug"].lower(), s["slug"].replace("_", " "),
                        s["slug"].lower().replace("_", " ")):
            out[variant] = s["seat"]
    return out


def table_block(cfg, seat, names):
    if seat["seat"] == cfg["gm_seat"]:
        block = {k: copy.deepcopy(cfg[k]) for k in GM_KEYS if k in cfg}
        block["seats"] = list(cfg["active_players"])
        block["seat_names"] = names
        block["seat_slugs"] = {s["seat"]: s["slug"] for s in cfg["seats"]}
        block["seat_of"] = _seat_of(cfg["seats"])
        block["forbidden_phrases"] = copy.deepcopy(cfg.get("forbidden_phrases", {}))
        block["silent_seats"] = list(cfg.get("silent_seats", []))
        block["auto_advance"] = cfg.get("auto_advance", True)
        for p in GM_PASSES:
            block[p] = copy.deepcopy(cfg[p])
        return block
    block = {"character_slug": seat["slug"], "pack_dir": cfg["pack_dir"], "seat_names": names}
    for p in SEAT_PASSES:
        block[p] = copy.deepcopy(cfg[p])
    return block


def build(table_cfg_path, out_dir):
    table_cfg_path = Path(table_cfg_path)
    cfg = yaml.safe_load(table_cfg_path.read_text(encoding="utf-8"))
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    casts = {s["slug"]: _cast(cfg["pack"], s["slug"]) for s in cfg["seats"]}
    names = {s["seat"]: casts[s["slug"]].get("name", s["slug"]) for s in cfg["seats"]}
    names["gm"] = names[cfg["gm_seat"]] = "GM"     # transcripts use "gm" for the GM's lines
    written = []
    for seat in cfg["seats"]:
        base = yaml.safe_load((REPO / seat["base"]).read_text(encoding="utf-8")) or {}
        doc = copy.deepcopy(base)
        agent = doc.setdefault("agent", {})
        cast = casts[seat["slug"]]
        agent["role"] = "table_gm" if seat["seat"] == cfg["gm_seat"] else "table_seat"
        agent["name"] = cast.get("name", seat["slug"])
        if cast.get("system_prompt"):
            agent["system_prompt"] = cast["system_prompt"]
        agent["tick_rate_ms"] = cfg["tick_rate_ms"]
        for stale in ("office", "office_role"):
            agent.pop(stale, None)
        agent["table"] = table_block(cfg, seat, names)
        doc["llm"] = copy.deepcopy(cfg["llm"])
        rel = table_cfg_path.resolve().relative_to(REPO) if table_cfg_path.resolve().is_relative_to(REPO) \
            else table_cfg_path.name
        text = HEADER.format(src=rel, base=seat["base"]) + yaml.dump(
            doc, Dumper=_Dumper, sort_keys=False, allow_unicode=True, width=100)
        path = out_dir / f"{seat['slug']}.yaml"
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("table_config", nargs="?", default=str(REPO / "config" / "table" / "ashiorid.yaml"))
    p.add_argument("--out", default=str(REPO / "config" / "workers" / "table"))
    args = p.parse_args(argv)
    for path in build(args.table_config, args.out):
        print(path.relative_to(REPO) if path.is_relative_to(REPO) else path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
